### PR TITLE
Add pendulum parser

### PR DESCRIPTION
**Pull request by ebma**
This PR adds a parser for the asset registries of the Pendulum and Amplitude networks.

This is a follow-up to https://github.com/colorfulnotion/xcm-global-registry/pull/40. By now we have the metadata available on Amplitude so that this parsing can actually be tested.

### CODE REVIEW

**Comment by ebma** [comment]
Hey @mkchungs, sorry for bothering you. Could you please have a look at this PR?

**Comment by mkchungs** [comment]
@ebma thank you for implementing the Pendulum/Amplitude parser. Everything looks good -- merging into main now

**Comment by mkchungs** [comment]
@ebma:
```
**** [kusama-2124] RegistryParser START (custom:true) ****
[kusama-2124] assetChainkey={"Token":"AMPE"}~kusama-2124 { assetType: 'Token', name: 'AMPE', symbol: 'AMPE', decimals: 12 }
[kusama-2124] Pendulum custom GAR parser
[kusama-2124] selected GAR - assetRegistry:metadata
2024-03-25 00:09:45        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: Unable to decode storage assetRegistry.metadata: entry 0:: createType(OrmlTraitsAssetRegistryAssetMetadata):: {"decimals":"u32","name":"Bytes","symbol":"Bytes","existentialDeposit":"u128","location":"Option<XcmVersionedMultiLocation>","additional":"RuntimeCommonAssetRegistryCustomMetadata"}:: Decoded input doesn't match input, received 0x0c0000002c5374656c6c617220545a5314545a532e73e8030000000000000000…34c94b2a4ba9e8b57b22547dcbb30f443c4cb02da3829a89aa1bd4780e4466ba (86 bytes), created 0x0c0000002c5374656c6c617220545a5314545a532e73e8030000000000000000…b02da3829a89aa1bd4780e4466ba000000000000000000000000000000000000 (104 bytes)
ERROR Error: Unable to decode storage assetRegistry.metadata: entry 0:: createType(OrmlTraitsAssetRegistryAssetMetadata):: {"decimals":"u32","name":"Bytes","symbol":"Bytes","existentialDeposit":"u128","location":"Option<XcmVersionedMultiLocation>","additional":"RuntimeCommonAssetRegistryCustomMetadata"}:: Decoded input doesn't match input, received 0x0c0000002c5374656c6c617220545a5314545a532e73e8030000000000000000…34c94b2a4ba9e8b57b22547dcbb30f443c4cb02da3829a89aa1bd4780e4466ba (86 bytes), created 0x0c0000002c5374656c6c617220545a5314545a532e73e8030000000000000000…b02da3829a89aa1bd4780e4466ba000000000000000000000000000000000000 (104 bytes)
    at RpcCore._newType (/home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:458:13)
    at RpcCore._formatStorageSetEntry (/home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:430:24)
    at /home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:405:25
    at Type.reduce (<anonymous>)
    at RpcCore._formatStorageSet (/home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:404:17)
    at /home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:378:58
    at Array.map (<anonymous>)
    at RpcCore._formatOutput (/home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:373:29)
    at RpcCore._formatResult (/home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)
    at callWithRegistry (/home/runner/work/xcm-global-registry/xcm-global-registry/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
looks like the recent runtime upgrade broke amplitude's asset parsing

**Comment by mkchungs** [comment]
Will Disablw amplitude for now

**Comment by ebma** [comment]
Hey @mkchungs, you are right and we introduced changes to the `CustomMetadata` without adding a migration which is why it's not decoding properly. We aim to fix this by the end of next week, I'll let you know once it's fixed 👍

**Comment by ebma** [comment]
Hey @mkchungs, the asset registry on Amplitude is back up so you can enable it again 😬

**Pull request merged**
